import json
import os
from pathlib import Path

CASES_DIR = Path(__file__).parent / "cases"
CASES_DIR.mkdir(parents=True, exist_ok=True)

# Define 20 cases
cases_data = [
    {
        "name": "c4-context-fintech",
        "pattern": "c4-context",
        "w": 1600,
        "h": 900,
        "prompt": "Build a C4 Context diagram for the fintech platform 'PayFlow Platform'. It includes 3 user personas (Customer, Merchant, Admin), the core PayFlow system, and 8 external systems (Payment Processor, KYC Provider, Fraud Detection, Banking API, Email Service, SMS Gateway, Analytics Platform, Regulatory Reporting). Define relationships for all interfaces.",
        "shapes": [
            ("user_cust", "Customer", "user-stated"),
            ("user_merch", "Merchant", "user-stated"),
            ("user_adm", "Admin", "user-stated"),
            ("sys_core", "PayFlow Platform", "user-stated"),
            ("sys_pay", "Payment Processor", "integration-docs"),
            ("sys_kyc", "KYC Provider", "compliance-spec"),
            ("sys_fraud", "Fraud Detection", "security-policy"),
            ("sys_bank", "Banking API", "banking-spec"),
            ("sys_email", "Email Service", "infra-spec"),
            ("sys_sms", "SMS Gateway", "infra-spec"),
            ("sys_analytics", "Analytics Platform", "bi-reqs"),
            ("sys_reg", "Regulatory Reporting", "compliance-spec"),
        ],
        "edges": [
            ("user_cust", "sys_core", "Uses app", "user-stated"),
            ("user_merch", "sys_core", "Uses portal", "user-stated"),
            ("user_adm", "sys_core", "Manages", "user-stated"),
            ("sys_core", "sys_pay", "Processes pay", "integration-docs"),
            ("sys_core", "sys_kyc", "Verifies identity", "compliance-spec"),
            ("sys_core", "sys_fraud", "Checks tx", "security-policy"),
            ("sys_core", "sys_bank", "Settles funds", "banking-spec"),
            ("sys_core", "sys_email", "Sends alert", "infra-spec"),
            ("sys_core", "sys_sms", "Sends OTP", "infra-spec"),
            ("sys_core", "sys_analytics", "Streams logs", "bi-reqs"),
            ("sys_core", "sys_reg", "Submits reports", "compliance-spec"),
            ("sys_pay", "sys_bank", "Reconciles", "banking-spec"),
            ("sys_kyc", "sys_reg", "Audits KYC", "compliance-spec"),
            ("sys_fraud", "sys_analytics", "Reports fraud", "bi-reqs"),
            ("user_cust", "sys_pay", "Enters card details", "user-stated"),
            ("user_merch", "sys_pay", "Receives payouts", "user-stated"),
            ("sys_core", "user_cust", "Notifies Customer", "user-stated"),
            ("sys_core", "user_merch", "Notifies Merchant", "user-stated"),
            ("sys_core", "user_adm", "Alerts Admin", "user-stated"),
            ("user_adm", "sys_analytics", "Views dashboard", "bi-reqs"),
        ]
    },
    {
        "name": "c4-container-ecommerce",
        "pattern": "c4-container",
        "w": 1800,
        "h": 1000,
        "prompt": "Create a C4 Container diagram for an E-commerce system containing: Web App, Mobile BFF, API Gateway, Product Service, Order Service, Cart Service, User Service, Search Service, Notification Service, and CDN. It integrates with external Payment Gateway, Shipping API, and Recommendation Engine.",
        "shapes": [
            ("cont_web", "Web App", "user-stated"),
            ("cont_bff", "Mobile BFF", "user-stated"),
            ("cont_gw", "API Gateway", "user-stated"),
            ("cont_prod", "Product Service", "user-stated"),
            ("cont_order", "Order Service", "user-stated"),
            ("cont_cart", "Cart Service", "user-stated"),
            ("cont_user", "User Service", "user-stated"),
            ("cont_search", "Search Service", "user-stated"),
            ("cont_notif", "Notification Service", "user-stated"),
            ("cont_cdn", "CDN", "user-stated"),
            ("ext_pay", "Payment Gateway", "integration-docs"),
            ("ext_ship", "Shipping API", "logistics-docs"),
            ("ext_recs", "Recommendation Engine", "ai-docs"),
            ("user_buyer", "Buyer", "user-stated"),
            ("user_admin", "Ecom Admin", "user-stated"),
        ],
        "edges": [
            ("user_buyer", "cont_cdn", "Requests static site", "user-stated"),
            ("user_buyer", "cont_web", "Views frontend", "user-stated"),
            ("user_buyer", "cont_bff", "Uses mobile app", "user-stated"),
            ("cont_web", "cont_gw", "APIs", "user-stated"),
            ("cont_bff", "cont_gw", "APIs", "user-stated"),
            ("cont_gw", "cont_user", "Authenticates", "user-stated"),
            ("cont_gw", "cont_prod", "Gets catalog", "user-stated"),
            ("cont_gw", "cont_cart", "Manages cart", "user-stated"),
            ("cont_gw", "cont_order", "Places order", "user-stated"),
            ("cont_gw", "cont_search", "Searches items", "user-stated"),
            ("cont_order", "ext_pay", "Charges client", "integration-docs"),
            ("cont_order", "ext_ship", "Creates shipment", "logistics-docs"),
            ("cont_order", "cont_notif", "Triggers confirm", "user-stated"),
            ("cont_prod", "ext_recs", "Fetches similar items", "ai-docs"),
            ("cont_search", "cont_prod", "Syncs index", "user-stated"),
            ("cont_notif", "user_buyer", "Sends email", "user-stated"),
            ("user_admin", "cont_gw", "Manages inventory", "user-stated"),
            ("cont_gw", "cont_notif", "Broadcasts alert", "user-stated"),
            ("cont_cart", "cont_prod", "Validates pricing", "user-stated"),
            ("cont_order", "cont_cart", "Clears cart", "user-stated"),
            ("cont_order", "cont_user", "Validates address", "user-stated"),
            ("cont_web", "cont_cdn", "Loads assets", "user-stated"),
            ("cont_bff", "cont_prod", "Direct read", "user-stated"),
        ]
    },
    {
        "name": "c4-component-auth",
        "pattern": "c4-component",
        "w": 1600,
        "h": 900,
        "prompt": "UML component diagram showing the internal components of an Auth Service: OAuth Controller, Token Manager, Session Store, MFA Handler, RBAC Engine, Audit Logger, Rate Limiter, User Repository, Password Hasher, and SAML Bridge. Connects to external LDAP Directory and Okta IdP.",
        "shapes": [
            ("comp_ctrl", "OAuth Controller", "user-stated"),
            ("comp_tok", "Token Manager", "user-stated"),
            ("comp_sess", "Session Store", "user-stated"),
            ("comp_mfa", "MFA Handler", "user-stated"),
            ("comp_rbac", "RBAC Engine", "user-stated"),
            ("comp_audit", "Audit Logger", "user-stated"),
            ("comp_rate", "Rate Limiter", "user-stated"),
            ("comp_repo", "User Repository", "user-stated"),
            ("comp_hash", "Password Hasher", "user-stated"),
            ("comp_saml", "SAML Bridge", "user-stated"),
            ("ext_ldap", "LDAP Directory", "corp-it"),
            ("ext_okta", "Okta IdP", "external-partner"),
            ("api_gw", "API Gateway", "user-stated"),
            ("db_user", "User Database", "user-stated"),
        ],
        "edges": [
            ("api_gw", "comp_rate", "Limits incoming traffic", "user-stated"),
            ("comp_rate", "comp_ctrl", "Routes clean requests", "user-stated"),
            ("comp_ctrl", "comp_saml", "Delegates federated login", "user-stated"),
            ("comp_saml", "ext_okta", "Redirects login", "external-partner"),
            ("comp_ctrl", "comp_repo", "Queries local credentials", "user-stated"),
            ("comp_repo", "ext_ldap", "Fails over to directory", "corp-it"),
            ("comp_repo", "db_user", "CRUD users", "user-stated"),
            ("comp_ctrl", "comp_hash", "Verifies pwd", "user-stated"),
            ("comp_ctrl", "comp_mfa", "Enforces OTP", "user-stated"),
            ("comp_ctrl", "comp_tok", "Generates JWT", "user-stated"),
            ("comp_ctrl", "comp_sess", "Creates session", "user-stated"),
            ("comp_ctrl", "comp_rbac", "Checks scope permissions", "user-stated"),
            ("comp_ctrl", "comp_audit", "Logs event", "user-stated"),
            ("comp_sess", "db_user", "Persists session states", "user-stated"),
            ("comp_tok", "comp_hash", "Signs payload", "user-stated"),
            ("comp_mfa", "comp_audit", "Logs MFA failure", "user-stated"),
            ("comp_rbac", "comp_repo", "Reads user roles", "user-stated"),
            ("comp_saml", "comp_tok", "Converts SAML to JWT", "user-stated"),
            ("comp_audit", "db_user", "Writes log records", "user-stated"),
            ("comp_sess", "comp_rate", "Cleans expired rate limits", "user-stated"),
            ("comp_repo", "comp_hash", "Encrypts input", "user-stated"),
        ]
    },
    {
        "name": "pipeline-kafka-flink",
        "pattern": "pipeline",
        "w": 1800,
        "h": 900,
        "prompt": "Build a streaming pipeline flow (left-to-right): Sources (IoT Sensors, Clickstream, Mobile Events, API Events) -> Kafka Topics (raw-events, enriched-events, alerts) -> Flink Jobs (Dedup, Enrich, Aggregate, Anomaly Detect) -> Sinks (Elasticsearch, S3 Data Lake, PagerDuty, Grafana Dashboard).",
        "shapes": [
            ("src_iot", "IoT Sensors", "user-stated"),
            ("src_click", "Clickstream", "user-stated"),
            ("src_mob", "Mobile Events", "user-stated"),
            ("src_api", "API Events", "user-stated"),
            ("kf_raw", "Kafka raw-events", "user-stated"),
            ("kf_enrich", "Kafka enriched-events", "user-stated"),
            ("kf_alerts", "Kafka alerts", "user-stated"),
            ("fl_dedup", "Flink Dedup Job", "user-stated"),
            ("fl_enrich", "Flink Enrich Job", "user-stated"),
            ("fl_agg", "Flink Aggregate Job", "user-stated"),
            ("fl_anomaly", "Flink Anomaly Detect", "user-stated"),
            ("snk_es", "Elasticsearch", "user-stated"),
            ("snk_s3", "S3 Data Lake", "user-stated"),
            ("snk_pd", "PagerDuty", "user-stated"),
            ("snk_graf", "Grafana Dashboard", "user-stated"),
            ("db_meta", "Metadata DB", "user-stated"),
        ],
        "edges": [
            ("src_iot", "kf_raw", "Publishes", "user-stated"),
            ("src_click", "kf_raw", "Publishes", "user-stated"),
            ("src_mob", "kf_raw", "Publishes", "user-stated"),
            ("src_api", "kf_raw", "Publishes", "user-stated"),
            ("kf_raw", "fl_dedup", "Consumes", "user-stated"),
            ("fl_dedup", "fl_enrich", "Streams deduped", "user-stated"),
            ("fl_enrich", "kf_enrich", "Publishes enriched", "user-stated"),
            ("fl_enrich", "db_meta", "Looks up metadata", "user-stated"),
            ("kf_enrich", "fl_agg", "Consumes enriched", "user-stated"),
            ("kf_enrich", "fl_anomaly", "Consumes enriched", "user-stated"),
            ("fl_agg", "snk_es", "Indexes metrics", "user-stated"),
            ("fl_agg", "snk_s3", "Archives batch data", "user-stated"),
            ("fl_anomaly", "kf_alerts", "Publishes anomalies", "user-stated"),
            ("kf_alerts", "snk_pd", "Triggers alerts", "user-stated"),
            ("kf_alerts", "snk_graf", "Displays alert overlays", "user-stated"),
            ("snk_es", "snk_graf", "Visualizes metrics", "user-stated"),
            ("fl_dedup", "kf_alerts", "Publishes parse errors", "user-stated"),
            ("src_api", "db_meta", "Writes configurations", "user-stated"),
            ("fl_enrich", "snk_s3", "Audits raw payload", "user-stated"),
            ("fl_anomaly", "snk_es", "Indexes anomaly logs", "user-stated"),
        ]
    },
    {
        "name": "pipeline-etl-warehouse",
        "pattern": "pipeline",
        "w": 1600,
        "h": 900,
        "prompt": "Create an AWS data warehouse ETL pipeline: Sources (PostgreSQL, MySQL, Salesforce API, S3 Raw) -> AWS Glue Crawlers + Glue ETL Jobs -> S3 Staging -> Redshift Cluster -> QuickSight Dashboards + SageMaker ML models.",
        "shapes": [
            ("src_pg", "PostgreSQL", "user-stated"),
            ("src_my", "MySQL", "user-stated"),
            ("src_sf", "Salesforce API", "user-stated"),
            ("src_s3", "S3 Raw Bucket", "user-stated"),
            ("glu_crawl", "AWS Glue Crawler", "user-stated"),
            ("glu_etl", "AWS Glue ETL Job", "user-stated"),
            ("stg_s3", "S3 Staging Bucket", "user-stated"),
            ("rs_clust", "Redshift Cluster", "user-stated"),
            ("bi_qs", "QuickSight Dashboard", "user-stated"),
            ("ml_sage", "SageMaker ML", "user-stated"),
            ("iam_role", "IAM Roles", "user-stated"),
            ("kms_keys", "KMS Keys", "user-stated"),
            ("vpc_peer", "VPC Peering", "user-stated"),
            ("cat_meta", "Glue Catalog", "user-stated"),
        ],
        "edges": [
            ("src_pg", "glu_crawl", "Scans metadata", "user-stated"),
            ("src_my", "glu_crawl", "Scans metadata", "user-stated"),
            ("src_sf", "src_s3", "Dumps hourly", "user-stated"),
            ("src_s3", "glu_crawl", "Scans files", "user-stated"),
            ("glu_crawl", "cat_meta", "Updates schema", "user-stated"),
            ("cat_meta", "glu_etl", "Informs schema", "user-stated"),
            ("src_pg", "glu_etl", "Extracts", "user-stated"),
            ("src_my", "glu_etl", "Extracts", "user-stated"),
            ("src_s3", "glu_etl", "Extracts", "user-stated"),
            ("glu_etl", "stg_s3", "Loads partitioned data", "user-stated"),
            ("stg_s3", "rs_clust", "COPY command loading", "user-stated"),
            ("rs_clust", "bi_qs", "Direct queries", "user-stated"),
            ("rs_clust", "ml_sage", "Fetches training data", "user-stated"),
            ("iam_role", "glu_etl", "Provides access", "user-stated"),
            ("kms_keys", "stg_s3", "Encrypts data", "user-stated"),
            ("vpc_peer", "src_pg", "Accesses secure subnets", "user-stated"),
            ("vpc_peer", "src_my", "Accesses secure subnets", "user-stated"),
            ("bi_qs", "ml_sage", "Displays ML inferences", "user-stated"),
            ("rs_clust", "cat_meta", "Shares catalog schema", "user-stated"),
            ("glu_etl", "cat_meta", "Writes job partitions", "user-stated"),
        ]
    },
    {
        "name": "swimlanes-zero-trust",
        "pattern": "swimlanes",
        "w": 1800,
        "h": 1000,
        "prompt": "Create a Zero-Trust network swimlanes diagram with 4 zones (Internet, DMZ, Internal Network, Data Center). Show elements like WAF, API Gateway, Auth Service, DB Cluster, Cache, Vault, and Vault Config across the lanes.",
        "shapes": [
            ("lane_int", "Internet Zone", "user-stated"),
            ("lane_dmz", "DMZ Zone", "user-stated"),
            ("lane_internal", "Internal Network", "user-stated"),
            ("lane_dc", "Data Center Zone", "user-stated"),
            ("user_ext", "External User", "user-stated"),
            ("bot_ext", "Bot Scanner", "user-stated"),
            ("waf", "WAF Engine", "user-stated"),
            ("alb", "Load Balancer", "user-stated"),
            ("apigw", "API Gateway", "user-stated"),
            ("auth_svc", "Auth Service", "user-stated"),
            ("web_app", "Web Server", "user-stated"),
            ("db_clust", "Database Cluster", "user-stated"),
            ("redis_cache", "Cache Layer", "user-stated"),
            ("vault", "Secrets Vault", "user-stated"),
            ("config_srv", "Config Server", "user-stated"),
            ("k8s_mesh", "Istio Service Mesh", "user-stated"),
        ],
        "edges": [
            ("user_ext", "waf", "HTTPS Request", "user-stated"),
            ("bot_ext", "waf", "Malicious Request", "user-stated"),
            ("waf", "alb", "Forwards allowed", "user-stated"),
            ("alb", "apigw", "Routes API call", "user-stated"),
            ("apigw", "auth_svc", "Authenticates token", "user-stated"),
            ("apigw", "web_app", "Proxy request", "user-stated"),
            ("web_app", "k8s_mesh", "Launches service request", "user-stated"),
            ("k8s_mesh", "redis_cache", "Reads/writes cache", "user-stated"),
            ("k8s_mesh", "db_clust", "SQL query", "user-stated"),
            ("k8s_mesh", "vault", "Fetches token credentials", "user-stated"),
            ("k8s_mesh", "config_srv", "Requests properties", "user-stated"),
            ("config_srv", "vault", "Decrypts config variables", "user-stated"),
            ("auth_svc", "redis_cache", "Stores user session", "user-stated"),
            ("auth_svc", "vault", "Gets RSA keys", "user-stated"),
            ("alb", "web_app", "Direct path", "user-stated"),
            ("waf", "user_ext", "Blocks bad payload", "user-stated"),
            ("apigw", "redis_cache", "Rate limits count", "user-stated"),
            ("web_app", "db_clust", "Saves transactions", "user-stated"),
            ("db_clust", "redis_cache", "Invalidates", "user-stated"),
            ("config_srv", "db_clust", "Fetches metadata", "user-stated"),
        ]
    },
    {
        "name": "swimlanes-sdlc",
        "pattern": "swimlanes",
        "w": 1800,
        "h": 1200,
        "prompt": "Create an SDLC toolchain swimlanes diagram with 5 phases (Plan, Develop, Build, Test, Deploy) containing: Jira, Confluence, VS Code, GitHub, SonarQube, Jenkins, Docker, Artifactory, Selenium, k6, Snyk, Trivy, ArgoCD, Kubernetes, Datadog, PagerDuty, and Terraform.",
        "shapes": [
            ("l_plan", "Plan Phase", "user-stated"),
            ("l_dev", "Develop Phase", "user-stated"),
            ("l_build", "Build Phase", "user-stated"),
            ("l_test", "Test Phase", "user-stated"),
            ("l_dep", "Deploy Phase", "user-stated"),
            ("t_jira", "Jira", "user-stated"),
            ("t_conf", "Confluence", "user-stated"),
            ("t_vscode", "VS Code", "user-stated"),
            ("t_git", "GitHub", "user-stated"),
            ("t_sonar", "SonarQube", "user-stated"),
            ("t_jenk", "Jenkins CI", "user-stated"),
            ("t_doc", "Docker Build", "user-stated"),
            ("t_art", "Artifactory", "user-stated"),
            ("t_sel", "Selenium", "user-stated"),
            ("t_k6", "k6 Performance", "user-stated"),
            ("t_snyk", "Snyk Scan", "user-stated"),
            ("t_trivy", "Trivy Scan", "user-stated"),
            ("t_argo", "ArgoCD GitOps", "user-stated"),
            ("t_k8s", "Kubernetes", "user-stated"),
            ("t_dd", "Datadog", "user-stated"),
            ("t_pd", "PagerDuty", "user-stated"),
            ("t_tf", "Terraform", "user-stated"),
        ],
        "edges": [
            ("t_jira", "t_conf", "References specs", "user-stated"),
            ("t_conf", "t_vscode", "Imports task outline", "user-stated"),
            ("t_vscode", "t_git", "Pushes commits", "user-stated"),
            ("t_git", "t_jenk", "Webhook trigger", "user-stated"),
            ("t_jenk", "t_sonar", "Sends static check metrics", "user-stated"),
            ("t_jenk", "t_snyk", "Code scanning dependency checks", "user-stated"),
            ("t_jenk", "t_doc", "Creates container", "user-stated"),
            ("t_doc", "t_trivy", "Scans image layers", "user-stated"),
            ("t_doc", "t_art", "Pushes container image", "user-stated"),
            ("t_art", "t_argo", "Signals new release package", "user-stated"),
            ("t_argo", "t_k8s", "Applies YAML manifest state", "user-stated"),
            ("t_k8s", "t_sel", "Tests endpoint integration", "user-stated"),
            ("t_k8s", "t_k6", "Loads testing traffic", "user-stated"),
            ("t_k8s", "t_dd", "Exports runtime metrics", "user-stated"),
            ("t_dd", "t_pd", "Triggers incidents", "user-stated"),
            ("t_pd", "t_jira", "Creates ticket automatically", "user-stated"),
            ("t_tf", "t_k8s", "Provisions infrastructure control", "user-stated"),
            ("t_git", "t_tf", "Triggers infrastructure plan", "user-stated"),
            ("t_sonar", "t_git", "Updates PR checks", "user-stated"),
            ("t_snyk", "t_jira", "Logs vulnerabilites", "user-stated"),
            ("t_trivy", "t_jira", "Logs image vulnerabilities", "user-stated"),
            ("t_dd", "t_jenk", "Sends build duration metrics", "user-stated"),
            ("t_k8s", "t_vscode", "Remote debugging attachment", "user-stated"),
            ("t_tf", "t_art", "Configures storage backends", "user-stated"),
        ]
    },
    {
        "name": "hub-radial-okta",
        "pattern": "hub-radial",
        "w": 1600,
        "h": 900,
        "prompt": "Create a Hub-and-Spoke diagram centered on Okta SSO. 12 connected apps: Salesforce, Slack, GitHub, AWS Console, Jira, Confluence, Zoom, Box, ServiceNow, Workday, Datadog, PagerDuty. Include MFA Provider connected to Okta.",
        "shapes": [
            ("okta_hub", "Okta Hub", "user-stated"),
            ("mfa_prov", "MFA Provider", "user-stated"),
            ("spk_sf", "Salesforce", "user-stated"),
            ("spk_slack", "Slack", "user-stated"),
            ("spk_git", "GitHub", "user-stated"),
            ("spk_aws", "AWS Console", "user-stated"),
            ("spk_jira", "Jira", "user-stated"),
            ("spk_conf", "Confluence", "user-stated"),
            ("spk_zoom", "Zoom", "user-stated"),
            ("spk_box", "Box", "user-stated"),
            ("spk_snow", "ServiceNow", "user-stated"),
            ("spk_wd", "Workday", "user-stated"),
            ("spk_dd", "Datadog", "user-stated"),
            ("spk_pd", "PagerDuty", "user-stated"),
        ],
        "edges": [
            ("okta_hub", "spk_sf", "Authenticates SAML", "user-stated"),
            ("okta_hub", "spk_slack", "Authenticates OIDC", "user-stated"),
            ("okta_hub", "spk_git", "Authenticates OIDC", "user-stated"),
            ("okta_hub", "spk_aws", "Authenticates SAML", "user-stated"),
            ("okta_hub", "spk_jira", "Authenticates SAML", "user-stated"),
            ("okta_hub", "spk_conf", "Authenticates SAML", "user-stated"),
            ("okta_hub", "spk_zoom", "Authenticates SAML", "user-stated"),
            ("okta_hub", "spk_box", "Authenticates SAML", "user-stated"),
            ("okta_hub", "spk_snow", "Authenticates SAML", "user-stated"),
            ("okta_hub", "spk_wd", "Authenticates OIDC", "user-stated"),
            ("okta_hub", "spk_dd", "Authenticates OIDC", "user-stated"),
            ("okta_hub", "spk_pd", "Authenticates OIDC", "user-stated"),
            ("mfa_prov", "okta_hub", "Pushes verification prompt", "user-stated"),
            ("spk_sf", "okta_hub", "Callback redirects back", "user-stated"),
            ("spk_slack", "okta_hub", "Callback redirects back", "user-stated"),
            ("spk_git", "okta_hub", "Callback redirects back", "user-stated"),
            ("spk_aws", "okta_hub", "Callback redirects back", "user-stated"),
            ("spk_wd", "okta_hub", "Syncs employee profiles", "user-stated"),
            ("okta_hub", "mfa_prov", "Requests MFA token authentication", "user-stated"),
        ]
    },
    {
        "name": "scope-columns-ciam",
        "pattern": "scope-columns",
        "w": 1800,
        "h": 1000,
        "prompt": "Create a diagram with two scope columns: Internal Platform (green boundary) containing Identity Platform, User Store, Policy Engine, Consent Manager, Session Service, Audit Service, Admin Portal, and Analytics Dashboard; External Integrations (black boundary) containing Okta, Auth0 CIAM, Twilio Verify, SendGrid, Stripe Identity, Experian KYC, and HubSpot CRM.",
        "shapes": [
            ("col_int", "Internal Platform", "user-stated"),
            ("col_ext", "External Integrations", "user-stated"),
            ("int_idp", "Identity Platform", "user-stated"),
            ("int_store", "User Store", "user-stated"),
            ("int_policy", "Policy Engine", "user-stated"),
            ("int_consent", "Consent Manager", "user-stated"),
            ("int_session", "Session Service", "user-stated"),
            ("int_audit", "Audit Service", "user-stated"),
            ("int_admin", "Admin Portal", "user-stated"),
            ("int_analytics", "Analytics Dashboard", "user-stated"),
            ("ext_okta", "Okta Workforce", "user-stated"),
            ("ext_auth0", "Auth0 CIAM", "user-stated"),
            ("ext_twilio", "Twilio Verify", "user-stated"),
            ("ext_sendgrid", "SendGrid", "user-stated"),
            ("ext_stripe", "Stripe Identity", "user-stated"),
            ("ext_experian", "Experian KYC", "user-stated"),
            ("ext_hubspot", "HubSpot CRM", "user-stated"),
        ],
        "edges": [
            ("int_idp", "int_store", "Reads user accounts", "user-stated"),
            ("int_idp", "int_policy", "Checks runtime constraints", "user-stated"),
            ("int_idp", "int_consent", "Verifies compliance approvals", "user-stated"),
            ("int_idp", "int_session", "Registers session validation", "user-stated"),
            ("int_idp", "int_audit", "Logs lifecycle security events", "user-stated"),
            ("int_admin", "int_idp", "Manages credentials", "user-stated"),
            ("int_admin", "int_store", "CRUD users", "user-stated"),
            ("int_idp", "ext_okta", "Federates employee login auth", "user-stated"),
            ("int_idp", "ext_auth0", "Syncs tenant logins", "user-stated"),
            ("int_idp", "ext_twilio", "Triggers multi-factor SMS auth", "user-stated"),
            ("int_idp", "ext_sendgrid", "Sends validation emails", "user-stated"),
            ("int_idp", "ext_stripe", "Verifies payment accounts", "user-stated"),
            ("int_idp", "ext_experian", "Verifies identity history details", "user-stated"),
            ("int_store", "ext_hubspot", "Syncs lead information fields", "user-stated"),
            ("int_analytics", "int_audit", "Analyzes event trace paths", "user-stated"),
            ("int_analytics", "ext_hubspot", "Syncs campaign metrics", "user-stated"),
            ("ext_okta", "int_session", "Verifies global session logs", "user-stated"),
            ("ext_auth0", "int_session", "Verifies app session logs", "user-stated"),
            ("ext_stripe", "int_audit", "Logs transaction check event", "user-stated"),
            ("ext_experian", "int_audit", "Logs verification passes", "user-stated"),
            ("int_consent", "ext_hubspot", "Enforces opt-out states", "user-stated"),
        ]
    },
    {
        "name": "tenant-namespace-multi",
        "pattern": "tenant-namespace",
        "w": 1800,
        "h": 1200,
        "prompt": "Create a multi-tenant namespace diagram. 3 Tenant containers (Tenant-Alpha, Tenant-Beta, Tenant-Gamma), each containing a Kafka Namespace, Flink Jobs, PostgreSQL Schema, Redis Cache, and S3 Bucket. Shared infrastructure contains API Gateway, Control Plane, Monitoring Stack, and Secrets Manager.",
        "shapes": [
            ("cont_t1", "Tenant-Alpha", "user-stated"),
            ("cont_t2", "Tenant-Beta", "user-stated"),
            ("cont_t3", "Tenant-Gamma", "user-stated"),
            ("t1_kf", "T1 Kafka Topic", "user-stated"),
            ("t1_fl", "T1 Flink Job", "user-stated"),
            ("t1_db", "T1 PostgreSQL", "user-stated"),
            ("t1_rd", "T1 Redis Cache", "user-stated"),
            ("t1_s3", "T1 S3 Bucket", "user-stated"),
            ("t2_kf", "T2 Kafka Topic", "user-stated"),
            ("t2_fl", "T2 Flink Job", "user-stated"),
            ("t2_db", "T2 PostgreSQL", "user-stated"),
            ("t2_rd", "T2 Redis Cache", "user-stated"),
            ("t2_s3", "T2 S3 Bucket", "user-stated"),
            ("t3_kf", "T3 Kafka Topic", "user-stated"),
            ("t3_fl", "T3 Flink Job", "user-stated"),
            ("t3_db", "T3 PostgreSQL", "user-stated"),
            ("t3_rd", "T3 Redis Cache", "user-stated"),
            ("t3_s3", "T3 S3 Bucket", "user-stated"),
            ("sh_apigw", "API Gateway", "user-stated"),
            ("sh_control", "Control Plane", "user-stated"),
            ("sh_monitor", "Monitoring Stack", "user-stated"),
            ("sh_vault", "Secrets Manager", "user-stated"),
        ],
        "edges": [
            ("sh_apigw", "t1_kf", "Ingests Tenant-Alpha metrics", "user-stated"),
            ("sh_apigw", "t2_kf", "Ingests Tenant-Beta metrics", "user-stated"),
            ("sh_apigw", "t3_kf", "Ingests Tenant-Gamma metrics", "user-stated"),
            ("t1_kf", "t1_fl", "Processes events", "user-stated"),
            ("t1_fl", "t1_db", "Saves transactional logs", "user-stated"),
            ("t1_fl", "t1_rd", "Updates caching items", "user-stated"),
            ("t1_fl", "t1_s3", "Saves bulk archive data", "user-stated"),
            ("t2_kf", "t2_fl", "Processes events", "user-stated"),
            ("t2_fl", "t2_db", "Saves transactional logs", "user-stated"),
            ("t2_fl", "t2_rd", "Updates caching items", "user-stated"),
            ("t2_fl", "t2_s3", "Saves bulk archive data", "user-stated"),
            ("t3_kf", "t3_fl", "Processes events", "user-stated"),
            ("t3_fl", "t3_db", "Saves transactional logs", "user-stated"),
            ("t3_fl", "t3_rd", "Updates caching items", "user-stated"),
            ("t3_fl", "t3_s3", "Saves bulk archive data", "user-stated"),
            ("sh_control", "t1_fl", "Updates jobs", "user-stated"),
            ("sh_control", "t2_fl", "Updates jobs", "user-stated"),
            ("sh_control", "t3_fl", "Updates jobs", "user-stated"),
            ("t1_fl", "sh_monitor", "Streams metrics telemetry", "user-stated"),
            ("t2_fl", "sh_monitor", "Streams metrics telemetry", "user-stated"),
            ("t3_fl", "sh_monitor", "Streams metrics telemetry", "user-stated"),
            ("t1_fl", "sh_vault", "Decrypts password credentials", "user-stated"),
            ("t2_fl", "sh_vault", "Decrypts password credentials", "user-stated"),
            ("t3_fl", "sh_vault", "Decrypts password credentials", "user-stated"),
            ("sh_control", "sh_vault", "Secures configs", "user-stated"),
            ("sh_apigw", "sh_control", "Forwards admin configurations", "user-stated"),
        ]
    },
    {
        "name": "erd-crowfoot-saas",
        "pattern": "erd-crowfoot",
        "w": 1600,
        "h": 1000,
        "prompt": "Create a SaaS multi-tenant crow's-foot Entity-Relationship Diagram. Entities: Organization, Workspace, Project, Member, Task, Document, Tag, Comment, User, BillingAccount, Subscription, Invoice, AuditLog. Define typical relational cardinalities between them.",
        "shapes": [
            ("ent_org", "Organization", "user-stated"),
            ("ent_ws", "Workspace", "user-stated"),
            ("ent_proj", "Project", "user-stated"),
            ("ent_mem", "Member", "user-stated"),
            ("ent_task", "Task", "user-stated"),
            ("ent_doc", "Document", "user-stated"),
            ("ent_tag", "Tag", "user-stated"),
            ("ent_cmt", "Comment", "user-stated"),
            ("ent_usr", "User", "user-stated"),
            ("ent_bill", "BillingAccount", "user-stated"),
            ("ent_sub", "Subscription", "user-stated"),
            ("ent_inv", "Invoice", "user-stated"),
            ("ent_audit", "AuditLog", "user-stated"),
        ],
        "edges": [
            ("ent_org", "ent_ws", "1 to many", "user-stated"),
            ("ent_ws", "ent_proj", "1 to many", "user-stated"),
            ("ent_ws", "ent_mem", "1 to many", "user-stated"),
            ("ent_proj", "ent_task", "1 to many", "user-stated"),
            ("ent_proj", "ent_doc", "1 to many", "user-stated"),
            ("ent_task", "ent_cmt", "1 to many", "user-stated"),
            ("ent_task", "ent_tag", "many to many", "user-stated"),
            ("ent_usr", "ent_mem", "1 to many", "user-stated"),
            ("ent_org", "ent_bill", "1 to 1", "user-stated"),
            ("ent_bill", "ent_sub", "1 to many", "user-stated"),
            ("ent_sub", "ent_inv", "1 to many", "user-stated"),
            ("ent_org", "ent_audit", "1 to many", "user-stated"),
            ("ent_usr", "ent_audit", "1 to many", "user-stated"),
            ("ent_mem", "ent_task", "1 to many assigned", "user-stated"),
            ("ent_mem", "ent_doc", "1 to many created", "user-stated"),
            ("ent_mem", "ent_cmt", "1 to many authored", "user-stated"),
            ("ent_ws", "ent_tag", "1 to many", "user-stated"),
            ("ent_usr", "ent_bill", "1 to many managed", "user-stated"),
            ("ent_sub", "ent_org", "many to 1", "user-stated"),
            ("ent_inv", "ent_org", "many to 1", "user-stated"),
            ("ent_ws", "ent_audit", "1 to many", "user-stated"),
            ("ent_task", "ent_audit", "1 to many", "user-stated"),
            ("ent_doc", "ent_audit", "1 to many", "user-stated"),
            ("ent_proj", "ent_audit", "1 to many", "user-stated"),
        ]
    },
    {
        "name": "uml-class-domain",
        "pattern": "uml-class",
        "w": 1600,
        "h": 1000,
        "prompt": "Draw a UML Class diagram representing an E-commerce domain model. Classes: Person (abstract), Customer, Employee, Order, OrderLine, Product, Category, Payment, Shipment, Address, Review, Discount, Inventory, Supplier. Use correct generalization, composition, and association lines.",
        "shapes": [
            ("cls_person", "Person (abstract)", "user-stated"),
            ("cls_cust", "Customer", "user-stated"),
            ("cls_emp", "Employee", "user-stated"),
            ("cls_order", "Order", "user-stated"),
            ("cls_line", "OrderLine", "user-stated"),
            ("cls_prod", "Product", "user-stated"),
            ("cls_cat", "Category", "user-stated"),
            ("cls_pay", "Payment", "user-stated"),
            ("cls_ship", "Shipment", "user-stated"),
            ("cls_addr", "Address", "user-stated"),
            ("cls_rev", "Review", "user-stated"),
            ("cls_disc", "Discount", "user-stated"),
            ("cls_inv", "Inventory", "user-stated"),
            ("cls_supp", "Supplier", "user-stated"),
        ],
        "edges": [
            ("cls_cust", "cls_person", "generalization", "user-stated"),
            ("cls_emp", "cls_person", "generalization", "user-stated"),
            ("cls_cust", "cls_order", "association 1 to many", "user-stated"),
            ("cls_order", "cls_line", "composition 1 to many", "user-stated"),
            ("cls_line", "cls_prod", "association many to 1", "user-stated"),
            ("cls_prod", "cls_cat", "association many to many", "user-stated"),
            ("cls_order", "cls_pay", "composition 1 to many", "user-stated"),
            ("cls_order", "cls_ship", "association many to 1", "user-stated"),
            ("cls_cust", "cls_addr", "composition 1 to many", "user-stated"),
            ("cls_prod", "cls_rev", "association 1 to many", "user-stated"),
            ("cls_prod", "cls_disc", "association many to many", "user-stated"),
            ("cls_prod", "cls_inv", "association 1 to 1", "user-stated"),
            ("cls_prod", "cls_supp", "association many to many", "user-stated"),
            ("cls_emp", "cls_order", "association manages", "user-stated"),
            ("cls_cust", "cls_rev", "association writes", "user-stated"),
            ("cls_supp", "cls_addr", "composition supplier address", "user-stated"),
            ("cls_ship", "cls_addr", "association shipping address", "user-stated"),
            ("cls_pay", "cls_cust", "association paying customer", "user-stated"),
            ("cls_inv", "cls_supp", "association replenishment source", "user-stated"),
            ("cls_disc", "cls_cust", "association redeemed by", "user-stated"),
            ("cls_emp", "cls_cust", "association support contact", "user-stated"),
            ("cls_person", "cls_addr", "association primary residence", "user-stated"),
            ("cls_order", "cls_disc", "association applied discount", "user-stated"),
            ("cls_ship", "cls_emp", "association dispatched by", "user-stated"),
            ("cls_inv", "cls_line", "association reserves stock", "user-stated"),
            ("cls_supp", "cls_inv", "association supplies components", "user-stated"),
        ]
    },
    {
        "name": "sequence-checkout",
        "pattern": "sequence",
        "w": 1600,
        "h": 900,
        "prompt": "Create a UML sequence diagram for a Checkout flow. Lifelines: Browser, API Gateway, Cart Service, Order Service, Payment Service, Inventory Service, Notification Service. Messages show the checkout request, cart fetch, inventory check, payment execution, order confirmation, and notifications.",
        "shapes": [
            ("ll_browser", "Browser", "user-stated"),
            ("ll_apigw", "API Gateway", "user-stated"),
            ("ll_cart", "Cart Service", "user-stated"),
            ("ll_order", "Order Service", "user-stated"),
            ("ll_pay", "Payment Service", "user-stated"),
            ("ll_inv", "Inventory Service", "user-stated"),
            ("ll_notif", "Notification Service", "user-stated"),
        ],
        "edges": [
            ("ll_browser", "ll_apigw", "POST /checkout", "user-stated"),
            ("ll_apigw", "ll_cart", "GET /cart/active", "user-stated"),
            ("ll_cart", "ll_apigw", "Cart data returned", "user-stated"),
            ("ll_apigw", "ll_order", "POST /order (create)", "user-stated"),
            ("ll_order", "ll_inv", "POST /inventory/reserve", "user-stated"),
            ("ll_inv", "ll_order", "Stock reserved (success)", "user-stated"),
            ("ll_order", "ll_pay", "POST /payment/charge", "user-stated"),
            ("ll_pay", "ll_order", "Charge successful (auth code)", "user-stated"),
            ("ll_order", "ll_notif", "POST /notify/order-created", "user-stated"),
            ("ll_notif", "ll_browser", "Websocket: order completed", "user-stated"),
            ("ll_order", "ll_apigw", "Order confirmation payload", "user-stated"),
            ("ll_apigw", "ll_browser", "201 Created (Order Details)", "user-stated"),
            ("ll_notif", "ll_pay", "Queries billing contact details", "user-stated"),
            ("ll_pay", "ll_notif", "Returns email", "user-stated"),
            ("ll_notif", "ll_cart", "Requests final state snapshot", "user-stated"),
            ("ll_cart", "ll_notif", "Returns items", "user-stated"),
            ("ll_browser", "ll_cart", "Clear local storage state", "user-stated"),
            ("ll_order", "ll_cart", "DELETE /cart/active", "user-stated"),
            ("ll_cart", "ll_order", "Cart deleted status", "user-stated"),
            ("ll_inv", "ll_notif", "Warns on low stock item thresholds", "user-stated"),
            ("ll_pay", "ll_inv", "Settles pending batch orders", "user-stated"),
            ("ll_inv", "ll_pay", "Batch settlement confirmations", "user-stated"),
            ("ll_browser", "ll_apigw", "GET /checkout/status", "user-stated"),
            ("ll_apigw", "ll_order", "GET /order/status", "user-stated"),
            ("ll_order", "ll_apigw", "Order status payload", "user-stated"),
            ("ll_apigw", "ll_browser", "200 OK (Status info)", "user-stated"),
            ("ll_order", "ll_inv", "POST /inventory/commit", "user-stated"),
            ("ll_inv", "ll_order", "Stock committed status", "user-stated"),
        ]
    },
    {
        "name": "tree-hierarchy-org",
        "pattern": "tree-hierarchy",
        "w": 1800,
        "h": 1000,
        "prompt": "Create an organization chart tree diagram: CEO at the top, branching to 5 VPs (VP Engineering, VP Product, VP Marketing, VP Sales, VP Finance). Each VP branches to 3 Directors. The Engineering directors branch further down to 3 Team Leads each.",
        "shapes": [
            ("ceo", "CEO", "user-stated"),
            ("vp_eng", "VP Engineering", "user-stated"),
            ("vp_prod", "VP Product", "user-stated"),
            ("vp_mkt", "VP Marketing", "user-stated"),
            ("vp_sales", "VP Sales", "user-stated"),
            ("vp_fin", "VP Finance", "user-stated"),
            ("dir_dev", "Dir Software Development", "user-stated"),
            ("dir_qa", "Dir Quality Assurance", "user-stated"),
            ("dir_ops", "Dir Cloud Operations", "user-stated"),
            ("dir_mgmt", "Dir Product Management", "user-stated"),
            ("dir_design", "Dir UX/UI Design", "user-stated"),
            ("dir_growth", "Dir Growth Product", "user-stated"),
            ("dir_brand", "Dir Brand Marketing", "user-stated"),
            ("dir_pr", "Dir Public Relations", "user-stated"),
            ("dir_perf", "Dir Performance Ads", "user-stated"),
            ("dir_ent", "Dir Enterprise Sales", "user-stated"),
            ("dir_smb", "Dir SMB Sales", "user-stated"),
            ("dir_ops_s", "Dir Sales Operations", "user-stated"),
            ("dir_acct", "Dir Accounting", "user-stated"),
            ("dir_fp", "Dir FP&A", "user-stated"),
            ("dir_tax", "Dir Tax & Treasury", "user-stated"),
            ("ld_fe", "Lead Frontend", "user-stated"),
            ("ld_be", "Lead Backend", "user-stated"),
            ("ld_mob", "Lead Mobile", "user-stated"),
            ("ld_aut", "Lead Test Automation", "user-stated"),
            ("ld_perf_t", "Lead Perf Testing", "user-stated"),
            ("ld_sec_t", "Lead Security Testing", "user-stated"),
            ("ld_sre", "Lead SRE", "user-stated"),
            ("ld_db", "Lead DBA", "user-stated"),
            ("ld_sec_o", "Lead Security Operations", "user-stated"),
        ],
        "edges": [
            ("ceo", "vp_eng", "manages", "user-stated"),
            ("ceo", "vp_prod", "manages", "user-stated"),
            ("ceo", "vp_mkt", "manages", "user-stated"),
            ("ceo", "vp_sales", "manages", "user-stated"),
            ("ceo", "vp_fin", "manages", "user-stated"),
            ("vp_eng", "dir_dev", "manages", "user-stated"),
            ("vp_eng", "dir_qa", "manages", "user-stated"),
            ("vp_eng", "dir_ops", "manages", "user-stated"),
            ("vp_prod", "dir_mgmt", "manages", "user-stated"),
            ("vp_prod", "dir_design", "manages", "user-stated"),
            ("vp_prod", "dir_growth", "manages", "user-stated"),
            ("vp_mkt", "dir_brand", "manages", "user-stated"),
            ("vp_mkt", "dir_pr", "manages", "user-stated"),
            ("vp_mkt", "dir_perf", "manages", "user-stated"),
            ("vp_sales", "dir_ent", "manages", "user-stated"),
            ("vp_sales", "dir_smb", "manages", "user-stated"),
            ("vp_sales", "dir_ops_s", "manages", "user-stated"),
            ("vp_fin", "dir_acct", "manages", "user-stated"),
            ("vp_fin", "dir_fp", "manages", "user-stated"),
            ("vp_fin", "dir_tax", "manages", "user-stated"),
            ("dir_dev", "ld_fe", "manages", "user-stated"),
            ("dir_dev", "ld_be", "manages", "user-stated"),
            ("dir_dev", "ld_mob", "manages", "user-stated"),
            ("dir_qa", "ld_aut", "manages", "user-stated"),
            ("dir_qa", "ld_perf_t", "manages", "user-stated"),
            ("dir_qa", "ld_sec_t", "manages", "user-stated"),
            ("dir_ops", "ld_sre", "manages", "user-stated"),
            ("dir_ops", "ld_db", "manages", "user-stated"),
            ("dir_ops", "ld_sec_o", "manages", "user-stated"),
        ]
    },
    {
        "name": "flowchart-dag-ci",
        "pattern": "flowchart-dag",
        "w": 1600,
        "h": 1000,
        "prompt": "Create a CI/CD pipeline flowchart containing: Start, Git Push, Lint Check, lint-pass decision, Unit Tests, Integration Tests, tests-pass decision, Build Docker Image, Push to Registry, Deploy Staging, Smoke Tests, smoke-pass decision, Deploy Production, Health Check, and End. Connect failure loops back.",
        "shapes": [
            ("node_start", "Start", "user-stated"),
            ("node_push", "Git Push", "user-stated"),
            ("node_lint", "Lint Check", "user-stated"),
            ("dec_lint", "Lint Passes?", "user-stated"),
            ("node_unit", "Unit Tests", "user-stated"),
            ("node_integ", "Integration Tests", "user-stated"),
            ("dec_tests", "Tests Pass?", "user-stated"),
            ("node_build", "Build Docker Image", "user-stated"),
            ("node_push_reg", "Push to Registry", "user-stated"),
            ("node_deploy_stg", "Deploy to Staging", "user-stated"),
            ("node_smoke", "Smoke Tests", "user-stated"),
            ("dec_smoke", "Smoke Passes?", "user-stated"),
            ("node_deploy_prod", "Deploy to Production", "user-stated"),
            ("node_health", "Health Check", "user-stated"),
            ("node_end", "End", "user-stated"),
            ("node_alert", "Alert Developer", "user-stated"),
        ],
        "edges": [
            ("node_start", "node_push", "triggers", "user-stated"),
            ("node_push", "node_lint", "runs", "user-stated"),
            ("node_lint", "dec_lint", "checks", "user-stated"),
            ("dec_lint", "node_unit", "Yes", "user-stated"),
            ("dec_lint", "node_alert", "No", "user-stated"),
            ("node_unit", "node_integ", "runs next", "user-stated"),
            ("node_integ", "dec_tests", "checks", "user-stated"),
            ("dec_tests", "node_build", "Yes", "user-stated"),
            ("dec_tests", "node_alert", "No", "user-stated"),
            ("node_build", "node_push_reg", "outputs", "user-stated"),
            ("node_push_reg", "node_deploy_stg", "installs", "user-stated"),
            ("node_deploy_stg", "node_smoke", "starts", "user-stated"),
            ("node_smoke", "dec_smoke", "checks", "user-stated"),
            ("dec_smoke", "node_deploy_prod", "Yes", "user-stated"),
            ("dec_smoke", "node_alert", "No", "user-stated"),
            ("node_deploy_prod", "node_health", "verifies", "user-stated"),
            ("node_health", "node_end", "completes", "user-stated"),
            ("node_alert", "node_push", "Retries commit", "user-stated"),
            ("node_health", "node_alert", "Failed health checks", "user-stated"),
            ("dec_lint", "node_end", "Terminate abort", "user-stated"),
        ]
    },
    {
        "name": "bpmn-order-process",
        "pattern": "bpmn-process",
        "w": 1800,
        "h": 1200,
        "prompt": "Create a BPMN order fulfillment process diagram. Pool: 'Order Management' with 3 lanes: Sales, Warehouse, Shipping. Process includes: Start event, Validate Order, check-credit gateway, Pick Items, Pack Items, parallel-packaging gateway, Generate Label, ship-method gateway, Ship Standard, Ship Express, Send Invoice, Update Status, Notify Customer, SLA breach event, and End event.",
        "shapes": [
            ("pool_order", "Order Management Pool", "user-stated"),
            ("lane_sales", "Sales Lane", "user-stated"),
            ("lane_wh", "Warehouse Lane", "user-stated"),
            ("lane_ship", "Shipping Lane", "user-stated"),
            ("ev_start", "Order Received Start", "user-stated"),
            ("t_val", "Validate Order", "user-stated"),
            ("gw_credit", "Credit Approved Gateway", "user-stated"),
            ("t_reject", "Reject Order", "user-stated"),
            ("t_pick", "Pick Items", "user-stated"),
            ("t_pack", "Pack Items", "user-stated"),
            ("gw_split", "Split Pack Gateway", "user-stated"),
            ("t_label", "Generate Label", "user-stated"),
            ("gw_method", "Ship Method Gateway", "user-stated"),
            ("t_standard", "Ship Standard", "user-stated"),
            ("t_express", "Ship Express", "user-stated"),
            ("t_invoice", "Send Invoice", "user-stated"),
            ("t_status", "Update Status", "user-stated"),
            ("t_notify", "Notify Customer", "user-stated"),
            ("ev_sla", "SLA Breach Event", "user-stated"),
            ("ev_end", "Order Completed End", "user-stated"),
        ],
        "edges": [
            ("ev_start", "t_val", "starts flow", "user-stated"),
            ("t_val", "gw_credit", "checks status", "user-stated"),
            ("gw_credit", "t_pick", "Yes", "user-stated"),
            ("gw_credit", "t_reject", "No", "user-stated"),
            ("t_pick", "t_pack", "moves items", "user-stated"),
            ("t_pack", "gw_split", "checks bulk size", "user-stated"),
            ("gw_split", "t_label", "Single box", "user-stated"),
            ("gw_split", "t_pick", "Needs split", "user-stated"),
            ("t_label", "gw_method", "checks priority", "user-stated"),
            ("gw_method", "t_standard", "Standard shipping", "user-stated"),
            ("gw_method", "t_express", "Express shipping", "user-stated"),
            ("t_standard", "t_invoice", "completes transit", "user-stated"),
            ("t_express", "t_invoice", "completes transit", "user-stated"),
            ("t_invoice", "t_status", "logs billing details", "user-stated"),
            ("t_status", "t_notify", "publishes status", "user-stated"),
            ("t_notify", "ev_end", "closes process", "user-stated"),
            ("t_pick", "ev_sla", "Timer active", "user-stated"),
            ("ev_sla", "t_notify", "Notifies supervisor", "user-stated"),
            ("t_reject", "t_notify", "Informs failure status", "user-stated"),
            ("t_val", "ev_sla", "Timer active", "user-stated"),
        ]
    },
    {
        "name": "grid-matrix-capabilities",
        "pattern": "grid-matrix",
        "w": 1800,
        "h": 1200,
        "prompt": "Create a 2D grid matrix classifying cloud capabilities. X-axis: Build, Buy, Partner. Y-axis: Core Platform, Data & Analytics, Security & Compliance, DevOps & Infra, Customer Engagement, Integration. Each cell should contain 1-2 distinct items.",
        "shapes": [
            ("cell_1_1", "Build Core Engine", "user-stated"),
            ("cell_1_2", "Buy SaaS Platform", "user-stated"),
            ("cell_1_3", "Partner System Integrator", "user-stated"),
            ("cell_2_1", "Build Custom Pipeline", "user-stated"),
            ("cell_2_2", "Buy Snowflake Warehouse", "user-stated"),
            ("cell_2_3", "Partner Databricks Analytics", "user-stated"),
            ("cell_3_1", "Build Custom IAM RBAC", "user-stated"),
            ("cell_3_2", "Buy Okta Auth0 SSO", "user-stated"),
            ("cell_3_3", "Partner Security Audit Corp", "user-stated"),
            ("cell_4_1", "Build Terraform Modules", "user-stated"),
            ("cell_4_2", "Buy Datadog SaaS APM", "user-stated"),
            ("cell_4_3", "Partner Managed AWS SRE", "user-stated"),
            ("cell_5_1", "Build Custom Portal UI", "user-stated"),
            ("cell_5_2", "Buy Salesforce Sales CRM", "user-stated"),
            ("cell_5_3", "Partner Hubspot Marketing", "user-stated"),
            ("cell_6_1", "Build Event Mesh Broker", "user-stated"),
            ("cell_6_2", "Buy MuleSoft ESB License", "user-stated"),
            ("cell_6_3", "Partner Confluent Cloud", "user-stated"),
            ("grid_core", "Core Platform", "user-stated"),
            ("grid_data", "Data & Analytics", "user-stated"),
            ("grid_sec", "Security & Compliance", "user-stated"),
            ("grid_devops", "DevOps & Infra", "user-stated"),
            ("grid_cust", "Customer Engagement", "user-stated"),
            ("grid_integ", "Integration", "user-stated"),
            ("grid_build", "Build Strategy", "user-stated"),
            ("grid_buy", "Buy Strategy", "user-stated"),
            ("grid_partner", "Partner Strategy", "user-stated"),
        ],
        "edges": [
            ("cell_1_1", "cell_1_2", "Migration path", "user-stated"),
            ("cell_1_2", "cell_1_3", "Integration path", "user-stated"),
            ("cell_2_1", "cell_2_2", "Ingestion path", "user-stated"),
            ("cell_2_2", "cell_2_3", "Analytics link", "user-stated"),
            ("cell_3_1", "cell_3_2", "Federation link", "user-stated"),
            ("cell_3_2", "cell_3_3", "Audit validation", "user-stated"),
            ("cell_4_1", "cell_4_2", "Telemetry setup", "user-stated"),
            ("cell_4_2", "cell_4_3", "Managed operations", "user-stated"),
            ("cell_5_1", "cell_5_2", "Customer sync", "user-stated"),
            ("cell_5_2", "cell_5_3", "Marketing handoff", "user-stated"),
            ("cell_6_1", "cell_6_2", "Broker connection", "user-stated"),
            ("cell_6_2", "cell_6_3", "Managed Kafka link", "user-stated"),
            ("grid_build", "cell_1_1", "Applies to", "user-stated"),
            ("grid_buy", "cell_1_2", "Applies to", "user-stated"),
            ("grid_partner", "cell_1_3", "Applies to", "user-stated"),
        ]
    },
    {
        "name": "aws-3tier-webapp",
        "pattern": "scope-columns",
        "w": 1800,
        "h": 1000,
        "prompt": "Create an AWS 3-tier web app architecture. Inside a VPC container: Public Subnet (ALB, NAT Gateway, Bastion), Private App Subnet (ECS Fargate Cluster, ElastiCache Redis), Private Data Subnet (RDS Aurora Primary, RDS Aurora Replica, DynamoDB). External: Route 53, CloudFront, S3 Assets, Cognito, CloudWatch, and SNS. Use AWS icons.",
        "shapes": [
            ("vpc_cont", "AWS VPC", "user-stated"),
            ("sub_pub", "Public Subnet", "user-stated"),
            ("sub_app", "Private App Subnet", "user-stated"),
            ("sub_data", "Private Data Subnet", "user-stated"),
            ("aws_route53", "Route 53", "user-stated"),
            ("aws_cloudfront", "CloudFront CDN", "user-stated"),
            ("aws_s3", "S3 Web Assets", "user-stated"),
            ("aws_cognito", "Cognito User Pool", "user-stated"),
            ("aws_alb", "Application Load Balancer", "user-stated"),
            ("aws_nat", "NAT Gateway", "user-stated"),
            ("aws_bastion", "Bastion Host", "user-stated"),
            ("aws_ecs", "ECS Fargate Cluster", "user-stated"),
            ("aws_redis", "ElastiCache Redis", "user-stated"),
            ("aws_rds_p", "RDS Aurora Primary", "user-stated"),
            ("aws_rds_r", "RDS Aurora Replica", "user-stated"),
            ("aws_ddb", "DynamoDB Table", "user-stated"),
            ("aws_cw", "CloudWatch Logs", "user-stated"),
            ("aws_sns", "SNS Alerts", "user-stated"),
        ],
        "edges": [
            ("aws_route53", "aws_cloudfront", "DNS resolution", "user-stated"),
            ("aws_cloudfront", "aws_s3", "Loads static cache", "user-stated"),
            ("aws_cloudfront", "aws_alb", "Routes dynamic api requests", "user-stated"),
            ("aws_alb", "aws_ecs", "Targets container groups", "user-stated"),
            ("aws_ecs", "aws_cognito", "Verifies JWT signatures", "user-stated"),
            ("aws_ecs", "aws_redis", "Caching query checks", "user-stated"),
            ("aws_ecs", "aws_rds_p", "Performs writes SQL", "user-stated"),
            ("aws_ecs", "aws_rds_r", "Performs reads SQL", "user-stated"),
            ("aws_ecs", "aws_ddb", "NoSQL key-value CRUD", "user-stated"),
            ("aws_ecs", "aws_nat", "Outbound internet api requests", "user-stated"),
            ("aws_nat", "aws_cw", "Pushes flow logs metadata", "user-stated"),
            ("aws_rds_p", "aws_rds_r", "Aurora storage replication", "user-stated"),
            ("aws_cw", "aws_sns", "Alert thresholds trigger", "user-stated"),
            ("aws_ecs", "aws_cw", "Application console logging", "user-stated"),
            ("aws_bastion", "aws_ecs", "SSH secure tunneling debugs", "user-stated"),
            ("aws_route53", "aws_cognito", "Secure custom domains auth", "user-stated"),
            ("aws_route53", "aws_s3", "Alternative static lookup route", "user-stated"),
            ("aws_s3", "aws_cw", "Storage access auditing logs", "user-stated"),
        ]
    },
    {
        "name": "azure-microservices",
        "pattern": "c4-container",
        "w": 1800,
        "h": 1000,
        "prompt": "Create an Azure microservices container architecture. Inside AKS Cluster container: API Management (APIM), Auth Service, Product Service, Order Service, Notification Service, and Event Grid Hub. External: Azure AD B2C, CosmosDB, Azure Service Bus, Azure Blob Storage, Application Insights, Key Vault, and Azure Front Door. Use Azure icons.",
        "shapes": [
            ("aks_cont", "AKS Kubernetes Cluster", "user-stated"),
            ("az_fd", "Azure Front Door", "user-stated"),
            ("az_apim", "API Management APIM", "user-stated"),
            ("az_b2c", "Azure AD B2C", "user-stated"),
            ("svc_auth", "Auth Service Container", "user-stated"),
            ("svc_prod", "Product Service Container", "user-stated"),
            ("svc_order", "Order Service Container", "user-stated"),
            ("svc_notif", "Notification Service Container", "user-stated"),
            ("az_eg", "Event Grid Hub", "user-stated"),
            ("az_cosmos", "CosmosDB Data Store", "user-stated"),
            ("az_sb", "Azure Service Bus", "user-stated"),
            ("az_blob", "Azure Blob Storage", "user-stated"),
            ("az_ai", "Application Insights", "user-stated"),
            ("az_kv", "Azure Key Vault", "user-stated"),
        ],
        "edges": [
            ("az_fd", "az_apim", "Ingress traffic route", "user-stated"),
            ("az_apim", "svc_auth", "Authenticates", "user-stated"),
            ("az_apim", "svc_prod", "API requests catalog", "user-stated"),
            ("az_apim", "svc_order", "API requests order creation", "user-stated"),
            ("svc_auth", "az_b2c", "Token validation checks", "user-stated"),
            ("svc_prod", "az_cosmos", "Reads catalog item documents", "user-stated"),
            ("svc_order", "az_cosmos", "Writes client transaction states", "user-stated"),
            ("svc_order", "az_sb", "Publishes order events", "user-stated"),
            ("az_sb", "svc_notif", "Consumes trigger notifications", "user-stated"),
            ("svc_notif", "az_eg", "Dispatches transaction alerts", "user-stated"),
            ("svc_prod", "az_blob", "Retrieves item images assets", "user-stated"),
            ("aks_cont", "az_ai", "Exports platform trace telemetry", "user-stated"),
            ("svc_auth", "az_kv", "Fetches JWT signing keys credentials", "user-stated"),
            ("svc_order", "az_kv", "Fetches database connection properties", "user-stated"),
            ("az_apim", "az_ai", "Tracks API endpoint duration metrics", "user-stated"),
            ("az_eg", "az_blob", "Archived events storage trigger", "user-stated"),
            ("az_fd", "az_b2c", "Direct client logins path", "user-stated"),
            ("az_cosmos", "az_ai", "Tracks query executions logs", "user-stated"),
        ]
    },
    {
        "name": "gcp-data-platform",
        "pattern": "pipeline",
        "w": 1800,
        "h": 1000,
        "prompt": "Build a GCP data platform streaming & batch pipeline: Sources (Cloud SQL, Firestore, Pub/Sub Ingestion, Cloud Storage Raw) -> Processing (Dataflow Batch, Dataflow Stream, Dataproc Spark) -> Storage (BigQuery, Cloud Storage Processed, Bigtable) -> Consumers (Looker Dashboards, Vertex AI, Data Catalog, Cloud Functions Alerts). Use GCP icons.",
        "shapes": [
            ("gcp_sql", "Cloud SQL DB", "user-stated"),
            ("gcp_fs", "Firestore NoSQL", "user-stated"),
            ("gcp_pubsub", "Pub/Sub Ingestion", "user-stated"),
            ("gcp_gcs_r", "Cloud Storage Raw", "user-stated"),
            ("gcp_df_b", "Dataflow Batch Job", "user-stated"),
            ("gcp_df_s", "Dataflow Stream Job", "user-stated"),
            ("gcp_dataproc", "Dataproc Spark Cluster", "user-stated"),
            ("gcp_bq", "BigQuery Data Warehouse", "user-stated"),
            ("gcp_gcs_p", "Cloud Storage Processed", "user-stated"),
            ("gcp_bt", "Bigtable Database", "user-stated"),
            ("gcp_looker", "Looker Dashboards", "user-stated"),
            ("gcp_vertex", "Vertex AI Platform", "user-stated"),
            ("gcp_catalog", "Data Catalog Meta", "user-stated"),
            ("gcp_functions", "Cloud Functions Alerts", "user-stated"),
        ],
        "edges": [
            ("gcp_sql", "gcp_df_b", "Extracts database records batch", "user-stated"),
            ("gcp_fs", "gcp_df_s", "Extracts database CDC streams", "user-stated"),
            ("gcp_pubsub", "gcp_df_s", "Subscribes real-time streaming", "user-stated"),
            ("gcp_gcs_r", "gcp_dataproc", "Reads raw files directly", "user-stated"),
            ("gcp_df_b", "gcp_bq", "Loads clean batch files warehouse", "user-stated"),
            ("gcp_df_s", "gcp_bq", "Streams analytics payload warehouse", "user-stated"),
            ("gcp_df_s", "gcp_bt", "Writes real-time caching records", "user-stated"),
            ("gcp_dataproc", "gcp_gcs_p", "Writes spark metrics archives", "user-stated"),
            ("gcp_bq", "gcp_looker", "Direct dashboards report queries", "user-stated"),
            ("gcp_bq", "gcp_vertex", "Fetches ML features dataset", "user-stated"),
            ("gcp_bq", "gcp_catalog", "Indexes schema column schemas", "user-stated"),
            ("gcp_bq", "gcp_functions", "Query thresholds trigger pubsub", "user-stated"),
            ("gcp_functions", "gcp_pubsub", "Publishes slack warnings channels", "user-stated"),
            ("gcp_looker", "gcp_catalog", "Checks field governance classifications", "user-stated"),
            ("gcp_gcs_p", "gcp_bq", "External tables load source link", "user-stated"),
            ("gcp_df_b", "gcp_gcs_p", "Loads processed flat logs", "user-stated"),
            ("gcp_sql", "gcp_gcs_r", "Dumps exports nightly backup files", "user-stated"),
            ("gcp_fs", "gcp_catalog", "Indexes document schemas meta", "user-stated"),
        ]
    }
]

def make_test_cases():
    threshold_content = {
        "xml": {
            "min_vertices": 12,
            "min_edges": 10,
            "max_duplicate_ids": 0,
            "max_orphan_parents": 0,
            "max_missing_edge_geometry": 0
        },
        "visual": {
            "max_shape_overlaps": 0,
            "min_contour_count": 8,
            "max_blank_pct": 98,
            "min_edge_lines_detected": 4
        },
        "content": {
            "min_label_recall": 0.70,
            "max_phantom_labels": 35
        },
        "regression": {
            "max_pixel_diff_pct": 5.0
        }
    }

    for case in cases_data:
        case_dir = CASES_DIR / case["name"]
        case_dir.mkdir(parents=True, exist_ok=True)

        # 1. prompt.md
        with open(case_dir / "prompt.md", "w") as f:
            f.write(f"# {case['name']}\n\n{case['prompt']}\n\nUse the {case['pattern']} pattern.\n")

        # 2. expected.plan.json
        # Format elements
        containers = []
        shapes = []
        # Group C4 container or tenant boundaries as container shapes
        for sid, lbl, cite in case["shapes"]:
            if sid.startswith("cont_t") or sid == "pool_order" or sid == "vpc_cont" or sid == "aks_cont":
                containers.append({
                    "id": sid,
                    "label": lbl,
                    "cite": cite
                })
            else:
                shapes.append({
                    "id": sid,
                    "label": lbl,
                    "cite": cite
                })

        edges = []
        for index, (src, tgt, lbl, cite) in enumerate(case["edges"]):
            edges.append({
                "id": f"edge_{index}",
                "source": src,
                "target": tgt,
                "label": lbl,
                "cite": cite
            })

        plan = {
            "pattern": case["pattern"],
            "canvas": {"w": case["w"], "h": case["h"]},
            "containers": containers,
            "shapes": shapes,
            "edges": edges
        }

        with open(case_dir / "expected.plan.json", "w") as f:
            json.dump(plan, f, indent=2)

        # 3. thresholds.json
        # Customize min counts based on case details
        tc = dict(threshold_content)
        tc["xml"] = dict(threshold_content["xml"])
        tc["xml"]["min_vertices"] = len(case["shapes"])
        tc["xml"]["min_edges"] = len(case["edges"])
        tc["visual"] = dict(threshold_content["visual"])
        tc["visual"]["min_contour_count"] = max(8, len(case["shapes"]) - 4)

        with open(case_dir / "thresholds.json", "w") as f:
            json.dump(tc, f, indent=2)

        print(f"Generated case: {case['name']}")

if __name__ == "__main__":
    make_test_cases()
